Repository dodevops/cloudcontrol, pull requests merged in 2022-09, with the labels that each got.

#49 feature: version updates of various dependencies
  .gitignore
  Dockerfile
  build.sh
  build/Dockerfile.prefix
  ccc/ccc.go
  ccc/client/package-lock.json
  ccc/client/package.json
  ccc/client/src/App.vue
  ccc/client/src/components/Progress.vue
  ccc/go.mod
  ccc/go.sum
  feature/bitwarden/feature.yaml
  package-lock.json
  package.json
Labels: dependencies, go, javascript

#53 fix dependabot nanoid warning
  ccc/client/package-lock.json
  ccc/client/package.json
Labels: dependencies, javascript, dependabot

#52 fix: Fixes Bitwarden installation
  feature/bitwarden/install.sh
  flavour/tanzu/Dockerfile.flavour
Labels: bug, feature-bitwarden

#42 Refactoring of kubelogin
  README.md
  feature/kubernetes/feature.yaml
  feature/kubernetes/install.sh
Labels: enhancement, flavour-azure, feature-kubernetes

#45 Feature certificates
  README.md
  feature/_fish/install.sh
  feature/bitwarden/install.sh
  feature/certificates/feature.yaml
  feature/certificates/install.sh
  feature/jq/install.sh
  feature/kc/install.sh
  feature/kubernetes/install.sh
  feature/packages/install.sh
  feature/terraform/feature.yaml
  feature/timezone/install.sh
  feature/vim/install.sh
  flavour/aws/sample/docker-compose.yaml
  flavour/azure/sample/docker-compose.yaml
  flavour/simple/sample/docker-compose.yaml
  flavour/tanzu/sample/docker-compose.yaml
Labels: documentation, enhancement

#54 fix: Hotfix for certificates feature after deep tests
  feature/certificates/install.sh
  flavour/aws/Dockerfile.flavour
  flavour/azure/Dockerfile.flavour
  flavour/simple/Dockerfile.flavour
  flavour/tanzu/Dockerfile.flavour
Labels: bug

#55 fix: Fixing path for kubelogin
  feature/kubernetes/install.sh
Labels: bug, flavour-azure, feature-kubernetes
